name: Coverage Report

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest

      - name: Run tests and generate coverage
        run: |
          coverage run -m pytest
          coverage xml

      - name: Upload coverage to GitHub summary (opcional)
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml

      - name: Show coverage report in GitHub Summary
        run: |
          pip install lxml
          python -m coverage report